### DISCUSSION TITLE
all-in-one docker

### DISCUSSION THREAD

**Discussion by drguiritan** [specify/specify7#3509] [Announcements]
all-in-one_asset-server_1      /bin/sh -c ve/bin/python s ...   Up       8080/tcp
all-in-one_mariadb_1           docker-entrypoint.sh --max ...   Up       3306/tcp
all-in-one_nginx_1             /docker-entrypoint.sh ngin ...   Up       0.0.0.0:80->80/tcp,:::80->80/tcp
all-in-one_redis_1             docker-entrypoint.sh redis ...   Up       6379/tcp
all-in-one_report-runner_1     /docker-entrypoint.sh java ...   Up       8080/tcp
all-in-one_specify6_1          /bin/sh -c rsync -a --dele ...   Exit 0
all-in-one_specify7-worker_1   /opt/specify7/docker-entry ...   Up       8000/tcp
all-in-one_specify7_1          /opt/specify7/docker-entry ...   Up       8000/tcp

I've done up and running the docker images but when I access my host-machine ip address remotely the NGINX says error 502 BAD GATEWAY. Do I miss something? I'm not sure whether to touch the file nginx/specify.conf or something need to modify from nginx container. Your help is much appreciated.

**Comment by PhatWheZ** [comment]
Hi @drguiritan, I see you are just using HTTP for your nginx reverse proxy. This could cause issues with some browsers flagging the site as unsecure.
Double check your nginx.conf settings as it must list the server name in order to proxy through nginx. Also make sure that your FQDN for your instance is setup and that when you ping your FQDN, it replies from your host-machine IP

Here are the relevant snippets for your reference
### docker-compose.yml
```
  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "static-files-training:/volumes/static-files-training:ro"
      - "specify6:/volumes/specify6:ro"
      - "./nginx:/etc/nginx/conf.d:ro"
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
```
### nginx/specify.training.saiab.ac.za.conf
```
server {
    listen 80;
    server_name specify.training.saiab.ac.za;
    access_log off;
    error_log off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name specify.training.saiab.ac.za;

    ssl_certificate /etc/letsencrypt/live/specify.training.saiab.ac.za/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/specify.training.saiab.ac.za/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # serve static files directly
    location /static/ {
        root /volumes;
        rewrite ^/static/config/(.*)$ /specify6/config/$1 break;
        rewrite ^/static/depository/(.*)$ /static-files-training/depository/$1 break;
        rewrite ^/static/(.*)$ /static-files-training/frontend-static/$1 break;
    }

    # proxy these urls to the asset server
    location ~ ^/(fileget|fileupload|filedelete|getmetadata|testkey|web_asset_store.xml) {
        client_max_body_size 0;
        resolver 127.0.0.11 valid=30s;
        set $backend "http://asset-server-training:8080";
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # proxy everything else to specify 7
    location / {
        resolver 127.0.0.11 valid=30s;
        set $backend "http://specify7-training:8000";
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

}
```
