### ISSUE TITLE
Properly style readonly inputs

### ISSUE THREAD

**Issue by maxxxxxdlp** [specify/specify7#566]
![Screenshot from 2020-01-17 09-22-04](https://user-images.githubusercontent.com/40512816/72632312-e012b500-390a-11ea-9538-ded1ce0965c8.png)
Readonly inputs should have `disabled` attribute. It its current form, those fields have outline and look exactly like editable fields do

**Comment by maxxxxxdlp** [comment]
![Screenshot from 2020-01-20 08-29-42](https://user-images.githubusercontent.com/40512816/72742674-12b4eb80-3b5f-11ea-80d9-3f7789deb2a2.png)

Also, the `GUID` field on a `New Taxon` form is editable

**Comment by maxxxxxdlp** [comment]
Same problem here and with a lot of other fields

![Screenshot from 2020-01-20 08-43-29](https://user-images.githubusercontent.com/40512816/72743665-f5811c80-3b60-11ea-8c4c-e350c40f8e70.png)

**Comment by maxxxxxdlp** [comment]
I tested this. If a `readonly` field has content, then the user can do `CTRL+A` and `CTRL+C`, which is great

Still, the outline should not be there, and the fields should have special styles to make them be more visible

Here is the styles that can fix this:
```css
input.specify-field[type="text"][readonly] {
    background: #eee;
    color: #555;
}

input.specify-field[type="text"][readonly]:focus {
    outline: none;
}
```
