### ISSUE TITLE
Update `docker-compositions` to support `v7.11.0`+

### ISSUE THREAD

**Issue by grantfitzsimmons** [specify/specify7#6802]
Using the current `docker-compositions` deployment structure, we are receiving CSRF failed verification errors. This has been reported by users during the workshop at SPNHC and has been encountered by users at KU (test instance for herpetology initially had this issue)

https://github.com/specify/docker-compositions/pull/37

Before release, we need to make sure this is settled

**Comment by realVinayak** [comment]
FYI: Also happens consistently in local development deployments, if using port other than 80. I used to run specify at port 5050, by changing outer port to 5050 it [here](https://github.com/specify/specify7/blob/d0657c5c8d80412cf62cc704d85084f685b5ec2f/docker-compose.yml#L97). I've other stuff running at port 80, so have to use 5050 port.

For example, this is what I see:

![Image](https://github.com/user-attachments/assets/c633d1c8-0816-491b-a7ce-f697f687ceb0)



I thought it had to do with an upgrade or something. I think I got it running eventually, but don't remember how I fixed it. Also, here is the nginx block

```
  nginx:
    image: nginx:alpine
    ports:
      - "5050:80"
    volumes:
      - "static-files:/volumes/static-files:ro"
      - "./config:/volumes/specify-config:ro"
      - "webpack-output:/volumes/webpack-output:ro"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
```
